<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dm</string>
	</array>
	<key>name</key>
	<string>Dream Maker Mk2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type_definition</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dm</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.dm</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dm</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.dm</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.dm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>proc_definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*?)([A-Za-z]+)\(.*\)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.indent.dm2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function.dm2 entity.name.function.dm2</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function_definition.dm2</string>
					<key>end</key>
					<string>^(?!\1\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>proc_definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*?)(proc)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.indent.dm2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.storage.dm2</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.procsrange.dm2</string>
					<key>end</key>
					<string>^(?!\1\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc_definition</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type_definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*?)([A-Za-z\\]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.type.dm2</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.typerange.dm2</string>
					<key>end</key>
					<string>^(?!\1\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc_definitions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#proc_definition</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#var_definitions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type_definition</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var_definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*?)(var)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.indent.dm2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.storage.dm2</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.varsrange.dm2</string>
					<key>end</key>
					<string>^(?!\1\s)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.hurr.durr.dm2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dm2</string>
	<key>uuid</key>
	<string>1db75b2a-de90-4bc7-8290-034ae7439453</string>
</dict>
</plist>
